first commit
mate-academy/Eco_cosmetics pull request #244
Opened 2023-06-12 06:44 UTC by Faridun92

[DEMO LINK](https://Faridun92.github.io/Eco_cosmetics/).

2023-06-12 18:51 UTC, SanyaBratashchuk requested changes
1. ![image](https://github.com/mate-academy/Eco_cosmetics/assets/97547824/8b951136-a609-4ed7-a22a-797bb363cca0)
2. Add hover effects for images 
![image](https://github.com/mate-academy/Eco_cosmetics/assets/97547824/98d5c691-6002-48ef-bd81-f28374a549c7)
3. change year 
![image](https://github.com/mate-academy/Eco_cosmetics/assets/97547824/39b1aca6-0245-4c63-86f6-a301a3de5c0f)
4. Disable scroll when menu is open

2023-06-13 15:08 UTC, loralevitska requested changes
Please deploy your solution, and before review check demo_link. If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review
![image](https://github.com/mate-academy/Eco_cosmetics/assets/70009205/36553e12-1c58-4a70-949c-094f7e8f048b)

2023-06-14 07:24 UTC, etojeDenys requested changes
add z-index 
<img width="1373" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/70220667/23092d85-95df-44d0-941e-f6cd2d331489">

2023-06-14 16:49 UTC, TarasHoliuk commented
1. On screens with size where width > ~1140px image blinks on hover (see screenshot), it would be nice to fix it:
![image](https://github.com/mate-academy/Eco_cosmetics/assets/86923089/76535515-2371-48da-8631-f574c04c310f)

2. I'd expect this button to lead to the contact us section:
![image](https://github.com/mate-academy/Eco_cosmetics/assets/86923089/a42aa3ce-1ab7-4ea7-addc-6d79e2c578ab)

2023-06-14 16:50 UTC, TarasHoliuk requested changes
You did an amazing job :+1: 
Almost done, let's fix a few things (check comments)

2023-06-15 14:55 UTC, loralevitska requested changes
- I did a great job with the slider, for a better effect I think you need to increase only the size of the picture that was, because when you add another photo, everything jumps, I recorded how it happens on the video

Uploading Запись экрана 2023-06-15 в 17.46.21.mov…


- find more different photos from their real site. Your site will be cooler. Also you can link here by click on `shop` button and instagram icon in footer  https://www.instagram.com/witch_of_mountain_winds/

2023-06-16 14:31 UTC, loralevitska approved these changes
Well done)
Add right links 
![image](https://github.com/mate-academy/Eco_cosmetics/assets/70009205/095c0bee-411b-43e6-8941-4a1778f6040d)

2026-08-18 22:29 UTC, closed without merging