The task is completed
mate-academy/Eco_cosmetics pull request #281
Opened 2023-09-05 08:38 UTC by AndruhaMan

[DEMO LINK](https://AndruhaMan.github.io/Eco_cosmetics/)

2023-09-05 08:46 UTC, IvanFesenko requested changes
Good job. Check this case with scroll

https://github.com/mate-academy/Eco_cosmetics/assets/61904995/3b73cb54-aac8-4c10-a878-0d14aed06359

2023-09-05 09:08 UTC, volodymyr-soltys97 requested changes
Almost done!
Add `cursor: pointer` for this button and check it everywhere
<img width="368" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/64750958/adbd3820-65af-47b4-a91c-61988b8b25fc">

2023-09-05 09:08 UTC, volodymyr-soltys97 commented on src/index.html
> +            <a class="footer__link" href="tel: +380934476839">
```suggestion
            <a class="footer__link" href="tel:+380934476839">
```

2023-09-05 09:08 UTC, volodymyr-soltys97 commented on src/index.html
> +                >
```suggestion
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="20"
                  height="20"
                  viewBox="0 0 20 20"
                  fill="none"
                >
```

2023-09-05 09:22 UTC, volodymyr-soltys97 approved these changes
Well done 🔥

2023-09-25 12:21 UTC, anastasiiavorobiova reviewed
Great work! &#128170; &#129504;

2026-02-26 16:48 UTC, closed without merging