Eco_cosmetics
mate-academy/Eco_cosmetics pull request #317
Opened 2023-10-26 08:27 UTC by Andrii-Monko

[DEMO LINK](https://Andrii-Monko.github.io/Eco_cosmetics/)

2023-10-26 17:45 UTC, etojeDenys requested changes
1. let's center container on wide screens
<img width="840" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/70220667/f5a6d9e3-c002-4556-805f-4f260ff8a644">


2. you should stretch these lines to the edges of the screen
<img width="1499" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/70220667/8b07e356-63e3-4747-90cd-77b827bd4f85">


3. make all form fields required 
4. add some hovers to links
<img width="383" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/70220667/d2991ca3-cad4-46cc-90f7-303044d77c04">

2023-10-29 07:13 UTC, volodymyr-soltys97 requested changes
1. The background color should stretch to the full width as it is on the design
<img width="1512" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/64750958/1679dc59-e500-4da5-ad54-cfde698e139e">

2. Add hover effects for all clickable elements
<img width="442" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/64750958/16a987f8-6072-4192-bffc-b42b979c676a">

3. Make all these fields are required before sending
<img width="526" alt="image" src="https://github.com/mate-academy/Eco_cosmetics/assets/64750958/e92c9083-7a43-4f69-92c6-2fdce78ba78a">

2023-10-29 07:13 UTC, volodymyr-soltys97 commented on src/index.html
> +          Ukrain
```suggestion
          Ukraine
```

2023-10-29 07:13 UTC, volodymyr-soltys97 commented on src/index.html
> +          <a href="mail:support.mountain@gmail.com" class="contact__text">
```suggestion
          <a href="mailto:support.mountain@gmail.com" class="contact__text">
```

2023-10-29 07:13 UTC, volodymyr-soltys97 commented on src/index.html
> +        <div class="p">
Use a more descriptive classes name instead of p

2023-10-29 07:13 UTC, volodymyr-soltys97 commented on src/index.html
> +        </div>
Use a semantic tags everywhere for text

2023-10-30 15:35 UTC, loralevitska requested changes
You did an amazing job! Looks good! Let's do some improvements (check comments)

- add transition for underlining
- don't reload page after form submit, just send form and clear after that
- fix image jumping due to underline
![image](https://github.com/mate-academy/Eco_cosmetics/assets/70009205/f620ca28-c0af-4784-8a26-3e247ed6001e)
- 2023 
![image](https://github.com/mate-academy/Eco_cosmetics/assets/70009205/e4269c68-7d66-43a8-ab8c-7c80d4065f28)
- make smooth menu appear/disappear 
- fix it according design (tablet mode)
![image](https://github.com/mate-academy/Eco_cosmetics/assets/70009205/910eeb9e-6ef1-4c91-9b2e-8ef8ceb08c91)
- the cross icon in menu should be on the same position with burger-menu icon on page, please fix it

2023-10-31 11:32 UTC, IvanFesenko requested changes
- Hover effects should not effect other elements
https://github.com/mate-academy/Eco_cosmetics/assets/61904995/5aae6406-74f5-4343-a9bd-d51fee72de7d
- Look like redundant margin
![2023-10-31_13h31_24](https://github.com/mate-academy/Eco_cosmetics/assets/61904995/901b25c1-28cd-4f80-8c64-59334c8f2045)
- disable scroll in case menu is open
 - Add cursor: pointer to elements that are clickable- product card for example

2023-11-01 19:05 UTC, Andriy-Shymkiv approved these changes

2024-06-03 08:34 UTC, closed without merging