without adaptively for mobile
mate-academy/Eco_cosmetics pull request #35
Opened 2020-12-07 22:26 UTC by DarMatt

[DEMO LINK](https://DarMatt.github.io/Eco_cosmetics/)

2020-12-08 11:01 UTC, vsm2k17 reviewed
![image](https://user-images.githubusercontent.com/35385361/101474723-30946600-3954-11eb-97b8-b8fba4d7cc5e.png)
тут щось пішло не так

![image](https://user-images.githubusercontent.com/35385361/101474804-443fcc80-3954-11eb-97ca-9de47fe2fc96.png)
 дуже маленька клікабельна зона

![image](https://user-images.githubusercontent.com/35385361/101474910-5faad780-3954-11eb-8e73-9eab6acb76b9.png)
 зазвичай у textarea забирають горизонтальний ресайз

![image](https://user-images.githubusercontent.com/35385361/101475021-7fda9680-3954-11eb-87f0-919bd2a859cb.png)
залиш форму без методу і з пустим action щоб не було помилки при відправці даних


![image](https://user-images.githubusercontent.com/35385361/101475248-d34ce480-3954-11eb-9b89-831579ed2721.png)
напиши так щоб при кліку відкривалась програма для листування

![image](https://user-images.githubusercontent.com/35385361/101475616-4c4c3c00-3955-11eb-8188-4b8be9e6184e.png)
 ці лінки повинні скролити до відповідних блоків

ну і жду адаптив

2020-12-09 14:45 UTC, vsm2k17 reviewed
![image](https://user-images.githubusercontent.com/35385361/101633988-bb4a9300-3a30-11eb-8d08-6d882d6be9f5.png)
не змінюй шрифт при хавері, краще використай transform scale


![image](https://user-images.githubusercontent.com/35385361/101635715-02d21e80-3a33-11eb-81aa-d64c639ca14d.png)
кнопку shop видно при відкритті мобільного меню, додай z-index для меню і хрестика

![image](https://user-images.githubusercontent.com/35385361/101635823-24cba100-3a33-11eb-86f0-1b7eb739e9e7.png)
контент сторінки видно під меню, якщо плануєш додавати закривання меню після кліку на якусь із лінок за допомогою js, то тут можна зробити щоб меню закривало усе інше собою


![image](https://user-images.githubusercontent.com/35385361/101641375-58f69000-3a3a-11eb-9331-94be15cc4422.png)
 при скролі бургер меню погано видно, можна задати йому якийсь бекграунд

![image](https://user-images.githubusercontent.com/35385361/101643854-37e36e80-3a3d-11eb-8e88-3ed4496502b5.png)
тут не по дизайну, загалом підхід з absolute не дуже зручний, пропоную тобі пізінше коли дороблятимеш слайдер, переробити футер на grid, тоді можна буде задавати порядок елементу, за допомогою grid-tamplate-areas а зараз задай йому відступ від краю щоб було як на дизайні

хороша робота, але потрібно ще трохи допрацювати

2020-12-14 16:11 UTC, aionova requested changes
Хорошая работа! 

Кнопка Learn на маленьком экране прилегает к краю.
Бургер-меню, когда нажимаешь на пункт меню, так и остается на весь экран.

2020-12-24 16:03 UTC, vsm2k17 approved these changes
![image](https://user-images.githubusercontent.com/35385361/103098004-f1336e00-4611-11eb-8521-90dae141b83e.png)
тут погано видно видно бургер меню

в загальному хороша робота, залишилось додати js щоб закривати мобільне меню після кліку на якийсь пункт і слайдер

2021-01-23 20:28 UTC, closed without merging

2021-01-23 20:28 UTC, DarMatt commented
close