Eco_cosmetics
mate-academy/Eco_cosmetics pull request #45
Opened 2021-02-12 16:46 UTC by SofiiaAsieieva

[DEMO LINK](https://SofiiaAsieieva.github.io/Eco_cosmetics/).

2021-03-03 09:21 UTC, OlexandrBelyaev approved these changes

2021-03-03 09:21 UTC, OlexandrBelyaev commented on src/styles/footer/footer.scss
> +    text-align: center;
Все начебто посортовано за правилами, але групи правил ліпше відділити порожніми строками.

2021-03-03 09:21 UTC, OlexandrBelyaev commented on src/styles/main/sectionContact/contact.scss
> +      column-gap: 70px;
column-gap може працювати не для всіх браузерів, тож ліпше прописати додатково через -webkit-, -moz- абощо

2021-03-03 09:21 UTC, OlexandrBelyaev commented on src/styles/main/sectionContact/contact.scss
> +    @include desctop {
Тільки desktop)

2021-03-03 09:21 UTC, OlexandrBelyaev commented on src/styles/main/sectionIngredients/ingredients.scss
> +      column-gap: 0;
В grid використовується grid-gap або grid-columns-gap

2021-03-04 08:41 UTC, Vladimir-Beliy requested changes
![image](https://user-images.githubusercontent.com/60401137/109935188-fda10a80-7cd5-11eb-9688-b7850c909b99.png)

почему какие то названы с нижним подчеркиванием а какие то без?

2021-03-04 08:41 UTC, Vladimir-Beliy commented on src/styles/header/burger__nav.scss
> +.burger {
файл назван неправильно

2021-03-29 12:36 UTC, Vladimir-Beliy approved these changes

2026-02-02 20:10 UTC, closed without merging